const css = {

    m_0: { margin: "0" },
    mt_0: { marginTop: "0" },
    my_0: { marginBottom: "0", marginTop: "0" },
    mr_0: { marginRight: "0" },
    mx_0: { marginLeft: "0", marginRight: "0" },
    mb_0: { marginBottom: "0" },
    ml_0: { marginLeft: "0" },
    m_1: { margin: "0.25rem" },
    mt_1: { marginTop: "0.25rem" },
    my_1: { marginBottom: "0.25rem", marginTop: "0.25rem" },
    mr_1: { marginRight: "0.25rem" },
    mx_1: { marginLeft: "0.25rem", marginRight: "0.25rem" },
    mb_1: { marginBottom: "0.25rem" },
    ml_1: { marginLeft: "0.25rem" },
    m_2: { margin: "0.5rem" },
    mt_2: { marginTop: "0.5rem" },
    my_2: { marginBottom: "0.5rem", marginTop: "0.5rem" },
    mr_2: { marginRight: "0.5rem" },
    mx_2: { marginLeft: "0.5rem", marginRight: "0.5rem" }, 
    mb_2: { marginBottom: "0.5rem" }, 
    ml_2: { marginLeft: "0.5rem" }, 
    m_3: { margin: "1rem" }, 
    mt_3: { marginTop: "1rem" }, 
    my_3: { marginBottom: "1rem", marginTop: "1rem" }, 
    mr_3: { marginRight: "1rem" }, 
    mx_3: { marginLeft: "1rem", marginRight: "1rem" }, 
    mb_3: { marginBottom: "1rem" }, 
    ml_3: { marginLeft: "1rem" }, 
    m_4: { margin: "1.5rem" }, 
    mt_4: { marginTop: "1.5rem" }, 
    my_4: { marginBottom: "1.5rem", marginTop: "1.5rem" }, 
    mr_4: { marginRight: "1.5rem" }, 
    mx_4: { marginLeft: "1.5rem", marginRight: "1.5rem" }, 
    mb_4: { marginBottom: "1.5rem" }, 
    ml_4: { marginLeft: "1.5rem" }, 
    m_5: { margin: "3rem" }, 
    mt_5: { marginTop: "3rem" }, 
    my_5: { marginBottom: "3rem", marginTop: "3rem" }, 
    mr_5: { marginRight: "3rem" }, 
    mx_5: { marginLeft: "3rem", marginRight: "3rem" }, 
    mb_5: { marginBottom: "3rem" }, 
    ml_5: { marginLeft: "3rem" }, 
    p_0: { padding: "0" }, 
    pt_0: { paddingTop: "0" }, 
    py_0: { paddingBottom: "0", paddingTop: "0rem" }, 
    pr_0: { paddingRight: "0" }, 
    px_0: { paddingLeft: "0", paddingRight: "0" }, 
    pb_0: { paddingBottom: "0" }, 
    pl_0: { paddingLeft: "0" }, 
    p_1: { padding: "0.25rem" }, 
    pt_1: { paddingTop: "0.25rem" }, 
    py_1: { paddingBottom: "0.25rem", paddingTop: "0.25rem" }, 
    pr_1: { paddingRight: "0.25rem" }, 
    px_1: { paddingLeft: "0.25rem", paddingRight: "0.25rem" }, 
    pb_1: { paddingBottom: "0.25rem" }, 
    pl_1: { paddingLeft: "0.25rem" }, 
    p_2: { padding: "0.5rem" }, 
    pt_2: { paddingTop: "0.5rem" }, 
    py_2: { paddingBottom: "0.5rem", paddingTop: "0.5rem" }, 
    pr_2: { paddingRight: "0.5rem" }, 
    px_2: { paddingLeft: "0.5rem", paddingRight: "0.5rem" }, 
    pb_2: { paddingBottom: "0.5rem" }, 
    pl_2: { paddingLeft: "0.5rem" }, 
    p_3: { padding: "1rem" }, 
    pt_3: { paddingTop: "1rem" }, 
    py_3: { paddingBottom: "1rem", paddingTop: "1rem" }, 
    pr_3: { paddingRight: "1rem" }, 
    px_3: { paddingLeft: "1rem", paddingRight: "1rem" }, 
    pb_3: { paddingBottom: "1rem" }, 
    pl_3: { paddingLeft: "1rem" }, 
    p_4: { padding: "1.5rem" }, 
    pt_4: { paddingTop: "1.5rem" }, 
    py_4: { paddingBottom: "1.5rem", paddingTop: "1.5rem" }, 
    pr_4: { paddingRight: "1.5rem" }, 
    px_4: { paddingLeft: "1.5rem", paddingRight: "1.5rem" }, 
    pb_4: { paddingBottom: "1.5rem" }, 
    pl_4: { paddingLeft: "1.5rem" }, 
    p_5: { padding: "3rem" }, 
    pt_5: { paddingTop: "3rem" }, 
    py_5: { paddingBottom: "3rem", paddingTop: "3rem" }, 
    pr_5: { paddingRight: "3rem" }, 
    px_5: { paddingLeft: "3rem", paddingRight: "3rem" }, 
    pb_5: { paddingBottom: "3rem" }, 
    pl_5: { paddingLeft: "3rem" }

};

export default css;