const values = [0, 0.25, 0.5, 1, 1.5, 3];

let basic = {

    mb_0: { marginBottom: values[0] + "rem" },
    mb_1: { marginBottom: values[1] + "rem" },
    mb_2: { marginBottom: values[2] + "rem" },
    mb_3: { marginBottom: values[3] + "rem" },
    mb_4: { marginBottom: values[4] + "rem" },
    mb_5: { marginBottom: values[5] + "rem" },
    ml_0: { marginLeft: values[0] + "rem" },
    ml_1: { marginLeft: values[1] + "rem" },
    ml_2: { marginLeft: values[2] + "rem" },
    ml_3: { marginLeft: values[3] + "rem" },
    ml_4: { marginLeft: values[4] + "rem" },
    ml_5: { marginLeft: values[5] + "rem" },
    mr_0: { marginRight: values[0] + "rem" },
    mr_1: { marginRight: values[1] + "rem" },
    mr_2: { marginRight: values[2] + "rem" },
    mr_3: { marginRight: values[3] + "rem" },
    mr_4: { marginRight: values[4] + "rem" },
    mr_5: { marginRight: values[5] + "rem" },
    mt_0: { marginTop: values[0] + "rem" },
    mt_1: { marginTop: values[1] + "rem" },
    mt_2: { marginTop: values[2] + "rem" },
    mt_3: { marginTop: values[3] + "rem" },
    mt_4: { marginTop: values[4] + "rem" },
    mt_5: { marginTop: values[5] + "rem" },
    pb_0: { paddingBottom: values[0] + "rem" },
    pb_1: { paddingBottom: values[1] + "rem" },
    pb_2: { paddingBottom: values[2] + "rem" },
    pb_3: { paddingBottom: values[3] + "rem" },
    pb_4: { paddingBottom: values[4] + "rem" },
    pb_5: { paddingBottom: values[5] + "rem" },
    pl_0: { paddingLeft: values[0] + "rem" },
    pl_1: { paddingLeft: values[1] + "rem" },
    pl_2: { paddingLeft: values[2] + "rem" },
    pl_3: { paddingLeft: values[3] + "rem" },
    pl_4: { paddingLeft: values[4] + "rem" },
    pl_5: { paddingLeft: values[5] + "rem" },
    pr_0: { paddingRight: values[0] + "rem" },
    pr_1: { paddingRight: values[1] + "rem" },
    pr_2: { paddingRight: values[2] + "rem" },
    pr_3: { paddingRight: values[3] + "rem" },
    pr_4: { paddingRight: values[4] + "rem" },
    pr_5: { paddingRight: values[5] + "rem" },
    pt_0: { paddingTop: values[0] + "rem" },
    pt_1: { paddingTop: values[1] + "rem" },
    pt_2: { paddingTop: values[2] + "rem" },
    pt_3: { paddingTop: values[3] + "rem" },
    pt_4: { paddingTop: values[4] + "rem" },
    pt_5: { paddingTop: values[5] + "rem" }

};

let css = {
    ...basic,
    
    m_0: { ...basic.ml_0, ...basic.mr_0, ...basic.mb_0, ...basic.mt_0 },
    m_1: { ...basic.ml_1, ...basic.mr_1, ...basic.mb_1, ...basic.mt_1 },
    m_2: { ...basic.ml_2, ...basic.mr_2, ...basic.mb_2, ...basic.mt_2 },
    m_3: { ...basic.ml_3, ...basic.mr_3, ...basic.mb_3, ...basic.mt_3 },
    m_4: { ...basic.ml_4, ...basic.mr_4, ...basic.mb_4, ...basic.mt_4 },
    m_5: { ...basic.ml_5, ...basic.mr_5, ...basic.mb_5, ...basic.mt_5 },
    mx_0: { ...basic.ml_0, ...basic.mr_0 },
    mx_1: { ...basic.ml_1, ...basic.mr_1 },
    mx_2: { ...basic.ml_2, ...basic.mr_2 },
    mx_3: { ...basic.ml_3, ...basic.mr_3 },
    mx_4: { ...basic.ml_4, ...basic.mr_4 },
    mx_5: { ...basic.ml_5, ...basic.mr_5 },
    my_0: { ...basic.mb_0, ...basic.mt_0 },
    my_1: { ...basic.mb_1, ...basic.mt_1 },
    my_2: { ...basic.mb_2, ...basic.mt_2 },
    my_3: { ...basic.mb_3, ...basic.mt_3 },
    my_4: { ...basic.mb_4, ...basic.mt_4 },
    my_5: { ...basic.mb_5, ...basic.mt_5 },
    p_0: { ...basic.pl_0, ...basic.pr_0, ...basic.pb_0, ...basic.pt_0 },
    p_1: { ...basic.pl_1, ...basic.pr_1, ...basic.pb_1, ...basic.pt_1 },
    p_2: { ...basic.pl_2, ...basic.pr_2, ...basic.pb_2, ...basic.pt_2 },
    p_3: { ...basic.pl_3, ...basic.pr_3, ...basic.pb_3, ...basic.pt_3 },
    p_4: { ...basic.pl_4, ...basic.pr_4, ...basic.pb_4, ...basic.pt_4 },
    p_5: { ...basic.pl_5, ...basic.pr_5, ...basic.pb_5, ...basic.pt_5 },
    px_0: { ...basic.pl_0, ...basic.pr_0 },
    px_1: { ...basic.pl_1, ...basic.pr_1 },
    px_2: { ...basic.pl_2, ...basic.pr_2 },
    px_3: { ...basic.pl_3, ...basic.pr_3 },
    px_4: { ...basic.pl_4, ...basic.pr_4 },
    px_5: { ...basic.pl_5, ...basic.pr_5 },
    py_0: { ...basic.pb_0, ...basic.pt_0 },
    py_1: { ...basic.pb_1, ...basic.pt_1 },
    py_2: { ...basic.pb_2, ...basic.pt_2 },
    py_3: { ...basic.pb_3, ...basic.pt_3 },
    py_4: { ...basic.pb_4, ...basic.pt_4 },
    py_5: { ...basic.pb_5, ...basic.pt_5 }

};

export default css;